services:
  db: 
    image: postgres:16.3-bullseye
    container_name: postgres
    env_file: .env
    ports:
      - 5030:5432
    restart: always
    volumes:
      - backend_template_db:/var/lib/postgresql/data
    networks:
      - backend-template-net
    
volumes:
  backend_template_db:
    driver: local

networks:
  backend-template-net:
    driver: bridge